INSERT INTO `category_type`
VALUES ('1', '대분류');
INSERT INTO `category_type`
VALUES ('2', '소분류');
INSERT INTO `category_type`
VALUES ('3', '재료');
INSERT INTO `category_type`
VALUES ('4', '조리방법');
INSERT INTO `category_type`
VALUES ('5', '식이제한');
INSERT INTO `category_type`
VALUES ('6', '음식특성');
INSERT INTO `category_type`
VALUES ('7', '식사시간');
